### ISSUE TITLE
NullInjectorError: No provider for InjectionToken FirebaseAppConfigToken!

### ISSUE THREAD

**Issue by afonsobarrenha** [samuel-lf/ticket-me#2]
Hi Samuel, the error persist.

![image](https://user-images.githubusercontent.com/13354019/63852124-fc1eb580-c96d-11e9-80f1-435e3e4593fc.png)

**Comment by samuel-lf** [comment]
@afonsobarrenha Hi Afonso, I have seen the changelog. GitGuardian blocked the upload of my archive because my app-module.ts contains the APIKey of my firebase. I'll send in your e-mail the archive, just replace and will work.
